import {
  BarChart3,
  GitBranch,
  Network,
  Sparkles,
  Target,
  TrendingUp,
  Workflow,
} from 'lucide-react';

export const ALGORITHM_CATALOG = [
  {
    id: 'pagerank',
    name: 'PageRank',
    description: 'Find the most influential entities in the selected graph slice.',
    endpoint: '/analytics/centrality/pagerank',
    icon: TrendingUp,
    category: 'Centrality',
    accent: 'from-sky-500/20 via-blue-500/10 to-transparent',
    iconClass: 'text-sky-500',
    defaults: { top_k: 15 },
    usesWeights: true,
  },
  {
    id: 'degree',
    name: 'Degree',
    description: 'Surface the nodes with the highest number of direct connections.',
    endpoint: '/analytics/centrality/degree',
    icon: BarChart3,
    category: 'Centrality',
    accent: 'from-emerald-500/20 via-green-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    defaults: { top_k: 15 },
    usesWeights: true,
  },
  {
    id: 'betweenness',
    name: 'Betweenness',
    description: 'Detect bridge entities that connect different graph regions.',
    endpoint: '/analytics/centrality/betweenness',
    icon: GitBranch,
    category: 'Centrality',
    accent: 'from-amber-500/20 via-orange-500/10 to-transparent',
    iconClass: 'text-amber-500',
    defaults: { top_k: 15 },
    usesWeights: true,
  },
  {
    id: 'louvain',
    name: 'Louvain',
    description: 'Group the dataset into communities based on dense relationships.',
    endpoint: '/analytics/community/louvain',
    icon: Network,
    category: 'Community',
    accent: 'from-fuchsia-500/20 via-pink-500/10 to-transparent',
    iconClass: 'text-fuchsia-500',
    defaults: {},
    usesWeights: false,
  },
  {
    id: 'leiden',
    name: 'Leiden',
    description: 'Run more refined community detection for tighter cluster discovery.',
    endpoint: '/analytics/community/leiden',
    icon: Workflow,
    category: 'Community',
    accent: 'from-violet-500/20 via-purple-500/10 to-transparent',
    iconClass: 'text-violet-500',
    defaults: {},
    usesWeights: false,
  },
  {
    id: 'node-similarity',
    name: 'Similarity',
    description: 'Reveal entities with highly similar structural neighborhoods.',
    endpoint: '/analytics/similarity/nodes',
    icon: Target,
    category: 'Similarity',
    accent: 'from-cyan-500/20 via-sky-500/10 to-transparent',
    iconClass: 'text-cyan-500',
    defaults: { top_k: 20 },
    usesWeights: false,
  },
  {
    id: 'link-common-neighbors',
    name: 'Common Neighbors',
    description: 'Predict likely missing links using shared-neighbor overlap.',
    endpoint: '/analytics/link-prediction',
    icon: Sparkles,
    category: 'Prediction',
    accent: 'from-rose-500/20 via-pink-500/10 to-transparent',
    iconClass: 'text-rose-500',
    defaults: { top_k: 20, method: 'common_neighbors' },
    usesWeights: false,
  },
  {
    id: 'link-adamic-adar',
    name: 'Adamic Adar',
    description: 'Predict hidden links with stronger weight on rare shared neighbors.',
    endpoint: '/analytics/link-prediction',
    icon: Sparkles,
    category: 'Prediction',
    accent: 'from-indigo-500/20 via-blue-500/10 to-transparent',
    iconClass: 'text-indigo-500',
    defaults: { top_k: 20, method: 'adamic_adar' },
    usesWeights: false,
  },
];
