import {
  Activity,
  ArrowLeftRight,
  BarChart3,
  ChevronRight,
  GitBranch,
  Layers,
  Lightbulb,
  Network,
  Play,
  Search,
  Share2,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Zap,
} from 'lucide-react';

export const ALGORITHM_GROUPS = [
  { id: 'centrality', label: 'Centrality', accent: 'text-emerald-500' },
  { id: 'community', label: 'Community', accent: 'text-teal-500' },
  { id: 'prediction', label: 'Prediction', accent: 'text-amber-500' },
  { id: 'decomposition', label: 'Decomposition', accent: 'text-cyan-500' },
  { id: 'pathfinding', label: 'Pathfinding', accent: 'text-emerald-600' },
  { id: 'topology', label: 'Topology', accent: 'text-slate-500' },
];

const topKParam = {
  key: 'top_k',
  label: 'Top results',
  type: 'number',
  min: 1,
  max: 100,
  defaultValue: 15,
};

export const ALGORITHM_CATALOG = [
  {
    id: 'pagerank',
    name: 'PageRank',
    description: 'Find the most influential entities in the selected graph slice.',
    endpoint: '/analytics/centrality/pagerank',
    icon: TrendingUp,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'articlerank',
    name: 'ArticleRank',
    description: 'Rank influence in diverse graphs with a more robust authority score.',
    endpoint: '/analytics/centrality/articlerank',
    icon: BarChart3,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'degree',
    name: 'Degree',
    description: 'Surface the nodes with the highest number of direct connections.',
    endpoint: '/analytics/centrality/degree',
    icon: Activity,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'betweenness',
    name: 'Betweenness',
    description: 'Detect bridge entities that connect different graph regions.',
    endpoint: '/analytics/centrality/betweenness',
    icon: GitBranch,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'closeness',
    name: 'Closeness',
    description: 'Find entities that can reach the rest of the graph efficiently.',
    endpoint: '/analytics/centrality/closeness',
    icon: Target,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-cyan-500/10 to-transparent',
    iconClass: 'text-emerald-400',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'hits',
    name: 'HITS',
    description: 'Separate hub nodes from authority nodes in the same dataset.',
    endpoint: '/analytics/centrality/hits',
    icon: Users,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'louvain',
    name: 'Louvain',
    description: 'Group the dataset into communities based on dense relationships.',
    endpoint: '/analytics/community/louvain',
    icon: Network,
    group: 'community',
    accent: 'from-teal-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-teal-500',
    chipClass: 'border-teal-500/20 bg-teal-500/10 text-teal-600 dark:text-teal-300',
    activeClass: 'border-teal-500/25 bg-teal-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'leiden',
    name: 'Leiden',
    description: 'Run refined community detection for tighter cluster discovery.',
    endpoint: '/analytics/community/leiden',
    icon: Workflow,
    group: 'community',
    accent: 'from-teal-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-teal-500',
    chipClass: 'border-teal-500/20 bg-teal-500/10 text-teal-600 dark:text-teal-300',
    activeClass: 'border-teal-500/25 bg-teal-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'wcc',
    name: 'Connected Islands',
    description: 'Find disconnected islands and separate graph components.',
    endpoint: '/analytics/community/wcc',
    icon: Layers,
    group: 'community',
    accent: 'from-teal-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-teal-500',
    chipClass: 'border-teal-500/20 bg-teal-500/10 text-teal-600 dark:text-teal-300',
    activeClass: 'border-teal-500/25 bg-teal-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'triangle-count',
    name: 'Triangle Count',
    description: 'Measure local density by counting tight three-node structures.',
    endpoint: '/analytics/community/triangles',
    icon: Activity,
    group: 'community',
    accent: 'from-teal-500/15 via-cyan-500/10 to-transparent',
    iconClass: 'text-teal-500',
    chipClass: 'border-teal-500/20 bg-teal-500/10 text-teal-600 dark:text-teal-300',
    activeClass: 'border-teal-500/25 bg-teal-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'k-core',
    name: 'Core Analysis',
    description: 'Find the stable center of the graph with k-core decomposition.',
    endpoint: '/analytics/community/kcore',
    icon: Target,
    group: 'decomposition',
    accent: 'from-cyan-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-cyan-500',
    chipClass: 'border-cyan-500/20 bg-cyan-500/10 text-cyan-600 dark:text-cyan-300',
    activeClass: 'border-cyan-500/25 bg-cyan-500/10',
    usesWeights: false,
    params: [
      {
        key: 'k',
        label: 'Minimum core',
        type: 'number',
        min: 1,
        max: 20,
        defaultValue: 3,
      },
    ],
  },
  {
    id: 'node-similarity',
    name: 'Node Similarity',
    description: 'Reveal entities with highly similar structural neighborhoods.',
    endpoint: '/analytics/similarity/nodes',
    icon: Search,
    group: 'prediction',
    accent: 'from-amber-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-amber-500',
    chipClass: 'border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-300',
    activeClass: 'border-amber-500/25 bg-amber-500/10',
    usesWeights: false,
    params: [
      {
        key: 'top_k',
        label: 'Top pairs',
        type: 'number',
        min: 1,
        max: 100,
        defaultValue: 20,
      },
    ],
  },
  {
    id: 'link-common-neighbors',
    name: 'Common Neighbors',
    description: 'Predict likely missing links using shared-neighbor overlap.',
    endpoint: '/analytics/link-prediction',
    icon: Lightbulb,
    group: 'prediction',
    accent: 'from-amber-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-amber-500',
    chipClass: 'border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-300',
    activeClass: 'border-amber-500/25 bg-amber-500/10',
    usesWeights: false,
    params: [{ ...topKParam, defaultValue: 20 }, { key: 'method', type: 'hidden', defaultValue: 'common_neighbors' }],
  },
  {
    id: 'link-adamic-adar',
    name: 'Adamic Adar',
    description: 'Predict hidden links by giving more value to rare shared neighbors.',
    endpoint: '/analytics/link-prediction',
    icon: Zap,
    group: 'prediction',
    accent: 'from-amber-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-amber-500',
    chipClass: 'border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-300',
    activeClass: 'border-amber-500/25 bg-amber-500/10',
    usesWeights: false,
    params: [{ ...topKParam, defaultValue: 20 }, { key: 'method', type: 'hidden', defaultValue: 'adamic_adar' }],
  },
  {
    id: 'link-resource-allocation',
    name: 'Resource Allocation',
    description: 'Predict links by simulating resource flow across shared neighbors.',
    endpoint: '/analytics/link-prediction',
    icon: ArrowLeftRight,
    group: 'prediction',
    accent: 'from-amber-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-amber-500',
    chipClass: 'border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-300',
    activeClass: 'border-amber-500/25 bg-amber-500/10',
    usesWeights: false,
    params: [{ ...topKParam, defaultValue: 20 }, { key: 'method', type: 'hidden', defaultValue: 'resource_allocation' }],
  },
  {
    id: 'shortest-path',
    name: 'Shortest Path',
    description: 'Find the shortest route between two selected nodes.',
    endpoint: '/analytics/path/shortest',
    icon: Share2,
    group: 'pathfinding',
    accent: 'from-emerald-600/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-600',
    chipClass: 'border-emerald-600/20 bg-emerald-600/10 text-emerald-700 dark:text-emerald-300',
    activeClass: 'border-emerald-600/25 bg-emerald-600/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Source node', type: 'node-select', defaultValue: '' },
      { key: 'target_id', label: 'Target node', type: 'node-select', defaultValue: '' },
    ],
  },
  {
    id: 'bfs',
    name: 'BFS Traversal',
    description: 'Explore the graph layer by layer from a selected start node.',
    endpoint: '/analytics/path/traversal',
    icon: Zap,
    group: 'pathfinding',
    accent: 'from-emerald-600/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-emerald-600',
    chipClass: 'border-emerald-600/20 bg-emerald-600/10 text-emerald-700 dark:text-emerald-300',
    activeClass: 'border-emerald-600/25 bg-emerald-600/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Start node', type: 'node-select', defaultValue: '' },
      { key: 'method', type: 'hidden', defaultValue: 'bfs' },
    ],
  },
  {
    id: 'dfs',
    name: 'DFS Traversal',
    description: 'Explore the graph deeply from a selected start node.',
    endpoint: '/analytics/path/traversal',
    icon: ChevronRight,
    group: 'pathfinding',
    accent: 'from-emerald-600/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-600',
    chipClass: 'border-emerald-600/20 bg-emerald-600/10 text-emerald-700 dark:text-emerald-300',
    activeClass: 'border-emerald-600/25 bg-emerald-600/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Start node', type: 'node-select', defaultValue: '' },
      { key: 'method', type: 'hidden', defaultValue: 'dfs' },
    ],
  },
  {
    id: 'random-walk',
    name: 'Random Walk',
    description: 'Simulate a walk through the graph from a selected node.',
    endpoint: '/analytics/path/random-walk',
    icon: Play,
    group: 'pathfinding',
    accent: 'from-emerald-600/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-600',
    chipClass: 'border-emerald-600/20 bg-emerald-600/10 text-emerald-700 dark:text-emerald-300',
    activeClass: 'border-emerald-600/25 bg-emerald-600/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Start node', type: 'node-select', defaultValue: '' },
      { key: 'walk_length', label: 'Walk length', type: 'number', min: 1, max: 50, defaultValue: 10 },
      { key: 'walk_count', label: 'Walk count', type: 'number', min: 1, max: 20, defaultValue: 1 },
    ],
  },
  {
    id: 'topological-sort',
    name: 'Logical Sequence',
    description: 'Order nodes in a directed acyclic sequence when possible.',
    endpoint: '/analytics/topology/topological-sort',
    icon: ChevronRight,
    group: 'topology',
    accent: 'from-slate-500/15 via-slate-400/10 to-transparent',
    iconClass: 'text-slate-500',
    chipClass: 'border-slate-500/20 bg-slate-500/10 text-slate-600 dark:text-slate-300',
    activeClass: 'border-slate-500/25 bg-slate-500/10',
    usesWeights: false,
    params: [],
  },
];

export function getAlgorithmById(id) {
  return ALGORITHM_CATALOG.find((item) => item.id === id) || ALGORITHM_CATALOG[0];
}
