import {
  Activity,
  ArrowLeftRight,
  BarChart3,
  ChevronRight,
  GitBranch,
  Layers,
  Lightbulb,
  Network,
  Play,
  Search,
  Share2,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Zap,
} from 'lucide-react';

export const ALGORITHM_GROUPS = [
  { id: 'centrality', label: 'Centrality', accent: 'text-emerald-500' },
  { id: 'community', label: 'Community', accent: 'text-fuchsia-500' },
  { id: 'prediction', label: 'Prediction', accent: 'text-sky-500' },
  { id: 'decomposition', label: 'Decomposition', accent: 'text-amber-500' },
  { id: 'pathfinding', label: 'Pathfinding', accent: 'text-violet-500' },
  { id: 'topology', label: 'Topology', accent: 'text-rose-500' },
];

const topKParam = {
  key: 'top_k',
  label: 'Top results',
  type: 'number',
  min: 1,
  max: 100,
  defaultValue: 15,
};

export const ALGORITHM_CATALOG = [
  {
    id: 'pagerank',
    name: 'PageRank',
    description: 'Find the most influential entities in the selected graph slice.',
    endpoint: '/analytics/centrality/pagerank',
    icon: TrendingUp,
    group: 'centrality',
    accent: 'from-sky-500/15 via-blue-500/10 to-transparent',
    iconClass: 'text-sky-500',
    chipClass: 'border-sky-500/20 bg-sky-500/10 text-sky-600 dark:text-sky-300',
    activeClass: 'border-sky-500/25 bg-sky-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'articlerank',
    name: 'ArticleRank',
    description: 'Rank influence in diverse graphs with a more robust authority score.',
    endpoint: '/analytics/centrality/articlerank',
    icon: BarChart3,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'degree',
    name: 'Degree',
    description: 'Surface the nodes with the highest number of direct connections.',
    endpoint: '/analytics/centrality/degree',
    icon: Activity,
    group: 'centrality',
    accent: 'from-emerald-500/15 via-green-500/10 to-transparent',
    iconClass: 'text-green-500',
    chipClass: 'border-green-500/20 bg-green-500/10 text-green-600 dark:text-green-300',
    activeClass: 'border-green-500/25 bg-green-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'betweenness',
    name: 'Betweenness',
    description: 'Detect bridge entities that connect different graph regions.',
    endpoint: '/analytics/centrality/betweenness',
    icon: GitBranch,
    group: 'centrality',
    accent: 'from-amber-500/15 via-orange-500/10 to-transparent',
    iconClass: 'text-amber-500',
    chipClass: 'border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-300',
    activeClass: 'border-amber-500/25 bg-amber-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'closeness',
    name: 'Closeness',
    description: 'Find entities that can reach the rest of the graph efficiently.',
    endpoint: '/analytics/centrality/closeness',
    icon: Target,
    group: 'centrality',
    accent: 'from-cyan-500/15 via-sky-500/10 to-transparent',
    iconClass: 'text-cyan-500',
    chipClass: 'border-cyan-500/20 bg-cyan-500/10 text-cyan-600 dark:text-cyan-300',
    activeClass: 'border-cyan-500/25 bg-cyan-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'hits',
    name: 'HITS',
    description: 'Separate hub nodes from authority nodes in the same dataset.',
    endpoint: '/analytics/centrality/hits',
    icon: Users,
    group: 'centrality',
    accent: 'from-indigo-500/15 via-blue-500/10 to-transparent',
    iconClass: 'text-indigo-500',
    chipClass: 'border-indigo-500/20 bg-indigo-500/10 text-indigo-600 dark:text-indigo-300',
    activeClass: 'border-indigo-500/25 bg-indigo-500/10',
    usesWeights: true,
    params: [topKParam],
  },
  {
    id: 'louvain',
    name: 'Louvain',
    description: 'Group the dataset into communities based on dense relationships.',
    endpoint: '/analytics/community/louvain',
    icon: Network,
    group: 'community',
    accent: 'from-fuchsia-500/15 via-pink-500/10 to-transparent',
    iconClass: 'text-fuchsia-500',
    chipClass: 'border-fuchsia-500/20 bg-fuchsia-500/10 text-fuchsia-600 dark:text-fuchsia-300',
    activeClass: 'border-fuchsia-500/25 bg-fuchsia-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'leiden',
    name: 'Leiden',
    description: 'Run refined community detection for tighter cluster discovery.',
    endpoint: '/analytics/community/leiden',
    icon: Workflow,
    group: 'community',
    accent: 'from-violet-500/15 via-purple-500/10 to-transparent',
    iconClass: 'text-violet-500',
    chipClass: 'border-violet-500/20 bg-violet-500/10 text-violet-600 dark:text-violet-300',
    activeClass: 'border-violet-500/25 bg-violet-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'wcc',
    name: 'Connected Islands',
    description: 'Find disconnected islands and separate graph components.',
    endpoint: '/analytics/community/wcc',
    icon: Layers,
    group: 'community',
    accent: 'from-teal-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-teal-500',
    chipClass: 'border-teal-500/20 bg-teal-500/10 text-teal-600 dark:text-teal-300',
    activeClass: 'border-teal-500/25 bg-teal-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'triangle-count',
    name: 'Triangle Count',
    description: 'Measure local density by counting tight three-node structures.',
    endpoint: '/analytics/community/triangles',
    icon: Activity,
    group: 'community',
    accent: 'from-rose-500/15 via-pink-500/10 to-transparent',
    iconClass: 'text-rose-500',
    chipClass: 'border-rose-500/20 bg-rose-500/10 text-rose-600 dark:text-rose-300',
    activeClass: 'border-rose-500/25 bg-rose-500/10',
    usesWeights: false,
    params: [],
  },
  {
    id: 'k-core',
    name: 'Core Analysis',
    description: 'Find the stable center of the graph with k-core decomposition.',
    endpoint: '/analytics/community/kcore',
    icon: Target,
    group: 'decomposition',
    accent: 'from-amber-500/15 via-yellow-500/10 to-transparent',
    iconClass: 'text-yellow-500',
    chipClass: 'border-yellow-500/20 bg-yellow-500/10 text-yellow-700 dark:text-yellow-300',
    activeClass: 'border-yellow-500/25 bg-yellow-500/10',
    usesWeights: false,
    params: [
      {
        key: 'k',
        label: 'Minimum core',
        type: 'number',
        min: 1,
        max: 20,
        defaultValue: 3,
      },
    ],
  },
  {
    id: 'node-similarity',
    name: 'Node Similarity',
    description: 'Reveal entities with highly similar structural neighborhoods.',
    endpoint: '/analytics/similarity/nodes',
    icon: Search,
    group: 'prediction',
    accent: 'from-cyan-500/15 via-sky-500/10 to-transparent',
    iconClass: 'text-sky-500',
    chipClass: 'border-sky-500/20 bg-sky-500/10 text-sky-600 dark:text-sky-300',
    activeClass: 'border-sky-500/25 bg-sky-500/10',
    usesWeights: false,
    params: [
      {
        key: 'top_k',
        label: 'Top pairs',
        type: 'number',
        min: 1,
        max: 100,
        defaultValue: 20,
      },
    ],
  },
  {
    id: 'link-common-neighbors',
    name: 'Common Neighbors',
    description: 'Predict likely missing links using shared-neighbor overlap.',
    endpoint: '/analytics/link-prediction',
    icon: Lightbulb,
    group: 'prediction',
    accent: 'from-rose-500/15 via-pink-500/10 to-transparent',
    iconClass: 'text-pink-500',
    chipClass: 'border-pink-500/20 bg-pink-500/10 text-pink-600 dark:text-pink-300',
    activeClass: 'border-pink-500/25 bg-pink-500/10',
    usesWeights: false,
    params: [{ ...topKParam, defaultValue: 20 }, { key: 'method', type: 'hidden', defaultValue: 'common_neighbors' }],
  },
  {
    id: 'link-adamic-adar',
    name: 'Adamic Adar',
    description: 'Predict hidden links by giving more value to rare shared neighbors.',
    endpoint: '/analytics/link-prediction',
    icon: Zap,
    group: 'prediction',
    accent: 'from-indigo-500/15 via-blue-500/10 to-transparent',
    iconClass: 'text-indigo-500',
    chipClass: 'border-indigo-500/20 bg-indigo-500/10 text-indigo-600 dark:text-indigo-300',
    activeClass: 'border-indigo-500/25 bg-indigo-500/10',
    usesWeights: false,
    params: [{ ...topKParam, defaultValue: 20 }, { key: 'method', type: 'hidden', defaultValue: 'adamic_adar' }],
  },
  {
    id: 'link-resource-allocation',
    name: 'Resource Allocation',
    description: 'Predict links by simulating resource flow across shared neighbors.',
    endpoint: '/analytics/link-prediction',
    icon: ArrowLeftRight,
    group: 'prediction',
    accent: 'from-violet-500/15 via-fuchsia-500/10 to-transparent',
    iconClass: 'text-violet-500',
    chipClass: 'border-violet-500/20 bg-violet-500/10 text-violet-600 dark:text-violet-300',
    activeClass: 'border-violet-500/25 bg-violet-500/10',
    usesWeights: false,
    params: [{ ...topKParam, defaultValue: 20 }, { key: 'method', type: 'hidden', defaultValue: 'resource_allocation' }],
  },
  {
    id: 'shortest-path',
    name: 'Shortest Path',
    description: 'Find the shortest route between two selected nodes.',
    endpoint: '/analytics/path/shortest',
    icon: Share2,
    group: 'pathfinding',
    accent: 'from-emerald-500/15 via-teal-500/10 to-transparent',
    iconClass: 'text-emerald-500',
    chipClass: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-300',
    activeClass: 'border-emerald-500/25 bg-emerald-500/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Source node', type: 'node-select', defaultValue: '' },
      { key: 'target_id', label: 'Target node', type: 'node-select', defaultValue: '' },
    ],
  },
  {
    id: 'bfs',
    name: 'BFS Traversal',
    description: 'Explore the graph layer by layer from a selected start node.',
    endpoint: '/analytics/path/traversal',
    icon: Zap,
    group: 'pathfinding',
    accent: 'from-teal-500/15 via-cyan-500/10 to-transparent',
    iconClass: 'text-teal-500',
    chipClass: 'border-teal-500/20 bg-teal-500/10 text-teal-600 dark:text-teal-300',
    activeClass: 'border-teal-500/25 bg-teal-500/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Start node', type: 'node-select', defaultValue: '' },
      { key: 'method', type: 'hidden', defaultValue: 'bfs' },
    ],
  },
  {
    id: 'dfs',
    name: 'DFS Traversal',
    description: 'Explore the graph deeply from a selected start node.',
    endpoint: '/analytics/path/traversal',
    icon: ChevronRight,
    group: 'pathfinding',
    accent: 'from-violet-500/15 via-purple-500/10 to-transparent',
    iconClass: 'text-violet-500',
    chipClass: 'border-violet-500/20 bg-violet-500/10 text-violet-600 dark:text-violet-300',
    activeClass: 'border-violet-500/25 bg-violet-500/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Start node', type: 'node-select', defaultValue: '' },
      { key: 'method', type: 'hidden', defaultValue: 'dfs' },
    ],
  },
  {
    id: 'random-walk',
    name: 'Random Walk',
    description: 'Simulate a walk through the graph from a selected node.',
    endpoint: '/analytics/path/random-walk',
    icon: Play,
    group: 'pathfinding',
    accent: 'from-lime-500/15 via-emerald-500/10 to-transparent',
    iconClass: 'text-lime-500',
    chipClass: 'border-lime-500/20 bg-lime-500/10 text-lime-600 dark:text-lime-300',
    activeClass: 'border-lime-500/25 bg-lime-500/10',
    usesWeights: false,
    params: [
      { key: 'source_id', label: 'Start node', type: 'node-select', defaultValue: '' },
      { key: 'walk_length', label: 'Walk length', type: 'number', min: 1, max: 50, defaultValue: 10 },
      { key: 'walk_count', label: 'Walk count', type: 'number', min: 1, max: 20, defaultValue: 1 },
    ],
  },
  {
    id: 'topological-sort',
    name: 'Logical Sequence',
    description: 'Order nodes in a directed acyclic sequence when possible.',
    endpoint: '/analytics/topology/topological-sort',
    icon: ChevronRight,
    group: 'topology',
    accent: 'from-rose-500/15 via-orange-500/10 to-transparent',
    iconClass: 'text-orange-500',
    chipClass: 'border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-300',
    activeClass: 'border-orange-500/25 bg-orange-500/10',
    usesWeights: false,
    params: [],
  },
];

export function getAlgorithmById(id) {
  return ALGORITHM_CATALOG.find((item) => item.id === id) || ALGORITHM_CATALOG[0];
}
